CREATE TABLE IF NOT EXISTS logs.ETL_LOG (
	PROCESS_NAME VARCHAR(60) NOT NULL,
	LOG_DATE DATE NOT NULL DEFAULT CURRENT_DATE, 
	START_TIME TIMESTAMP NOT NULL,
	END_TIME TIMESTAMP,
	STATUS VARCHAR(20) NOT NULL,
	ROWS_PROCESSED INTEGER DEFAULT 0,
	ERROR_MESSAGE TEXT,
	duration INTERVAL
);