<<<<<<<< HEAD:app-vol/initdb/06-tables-taskdb.sql
\c taskdb

CREATE TABLE IF NOT EXISTS LOGS.ETL_LOG (
	PROCESS_NAME VARCHAR(60) NOT NULL,
	LOG_DATE DATE NOT NULL DEFAULT CURRENT_DATE, 
	START_TIME TIMESTAMP NOT NULL,
	END_TIME TIMESTAMP,
	STATUS VARCHAR(20) NOT NULL,
	ROWS_PROCESSED INTEGER DEFAULT 0,
	ERROR_MESSAGE TEXT,
	duration TIMESTAMP
);

CREATE TABLE IF NOT EXISTS DS.ft_balance_f(
========
CREATE SCHEMA IF NOT EXISTS ds;

CREATE TABLE IF NOT EXISTS ds.ft_balance_f(
>>>>>>>> main:1TASK/1_task/Scripts/sql/sql_create_table.sql
	on_date       DATE NOT NULL,
    account_rk    NUMERIC NOT NULL,
    currency_rk   NUMERIC,
    balance_out   FLOAT,
	CONSTRAINT BALANCE_PKEY PRIMARY KEY (ON_DATE, ACCOUNT_RK)
);

<<<<<<<< HEAD:app-vol/initdb/06-tables-taskdb.sql
CREATE TABLE IF NOT EXISTS DS.ft_posting_f(
========
CREATE TABLE IF NOT EXISTS ds.ft_posting_f(
>>>>>>>> main:1TASK/1_task/Scripts/sql/sql_create_table.sql
	oper_date         DATE NOT NULL,
    credit_account_rk NUMERIC NOT NULL,
    debet_account_rk  NUMERIC NOT NULL,
    credit_amount     FLOAT,
    debet_amount      FLOAT
);

<<<<<<<< HEAD:app-vol/initdb/06-tables-taskdb.sql
CREATE TABLE IF NOT EXISTS DS.md_account_d (
========

CREATE TABLE IF NOT EXISTS ds.md_account_d (
>>>>>>>> main:1TASK/1_task/Scripts/sql/sql_create_table.sql
	DATA_ACTUAL_DATE DATE NOT NULL,
	DATA_ACTUAL_END_DATE DATE NOT NULL,
	ACCOUNT_RK NUMERIC NOT NULL,
	ACCOUNT_NUMBER VARCHAR(20) NOT NULL,
	CHAR_TYPE VARCHAR(1) NOT NULL,
	CURRENCY_RK NUMERIC NOT NULL,
	CURRENCY_CODE VARCHAR(3) NOT NULL,
	CONSTRAINT ACCOUNT_PKEY PRIMARY KEY (DATA_ACTUAL_DATE, ACCOUNT_RK)
);

<<<<<<<< HEAD:app-vol/initdb/06-tables-taskdb.sql
CREATE TABLE IF NOT EXISTS DS.md_currency_d (
========
CREATE TABLE IF NOT EXISTS ds.md_currency_d (
>>>>>>>> main:1TASK/1_task/Scripts/sql/sql_create_table.sql
	CURRENCY_RK NUMERIC NOT NULL,
	DATA_ACTUAL_DATE DATE NOT NULL,
	DATA_ACTUAL_END_DATE DATE,
	CURRENCY_CODE VARCHAR(3),
	CODE_ISO_CHAR VARCHAR(3),
	CONSTRAINT CURRENCY_PKEY PRIMARY KEY (CURRENCY_RK, DATA_ACTUAL_DATE)
);

<<<<<<<< HEAD:app-vol/initdb/06-tables-taskdb.sql
CREATE TABLE IF NOT EXISTS DS.md_exchange_rate_d (
========
CREATE TABLE IF NOT EXISTS ds.md_exchange_rate_d (
>>>>>>>> main:1TASK/1_task/Scripts/sql/sql_create_table.sql
	DATA_ACTUAL_DATE DATE NOT NULL,
	DATA_ACTUAL_END_DATE DATE,
	CURRENCY_RK NUMERIC NOT NULL,
	REDUCED_COURCE FLOAT,
	CODE_ISO_NUM VARCHAR(3),
	CONSTRAINT EXCHANGE_RATE_PKEY PRIMARY KEY (DATA_ACTUAL_DATE, CURRENCY_RK)
);

<<<<<<<< HEAD:app-vol/initdb/06-tables-taskdb.sql
CREATE TABLE IF NOT EXISTS DS.md_ledger_account_s (
========
CREATE TABLE IF NOT EXISTS ds.md_ledger_account_s (
>>>>>>>> main:1TASK/1_task/Scripts/sql/sql_create_table.sql
	CHAPTER CHARACTER(1),
	CHAPTER_NAME VARCHAR(16),
	SECTION_NUMBER INTEGER,
	SECTION_NAME VARCHAR(22),
	SUBSECTION_NAME VARCHAR(21),
	LEDGER1_ACCOUNT INTEGER,
	LEDGER1_ACCOUNT_NAME VARCHAR(47),
	LEDGER_ACCOUNT INTEGER NOT NULL,
	LEDGER_ACCOUNT_NAME VARCHAR(153),
	CHARACTERISTIC CHARACTER(1),
	IS_RESIDENT INTEGER,
	IS_RESERVE INTEGER,
	IS_RESERVED INTEGER,
	IS_LOAN INTEGER,
	IS_RESERVED_ASSETS INTEGER,
	IS_OVERDUE INTEGER,
	IS_INTEREST INTEGER,
	PAIR_ACCOUNT VARCHAR(5),
	START_DATE DATE NOT NULL,
	END_DATE DATE,
	IS_RUB_ONLY INTEGER,
	MIN_TERM VARCHAR(1),
	MIN_TERM_MEASURE VARCHAR(1),
	MAX_TERM VARCHAR(1),
	MAX_TERM_MEASURE VARCHAR(1),
	LEDGER_ACC_FULL_NAME_TRANSLIT VARCHAR(1),
	IS_REVALUATION VARCHAR(1),
	IS_CORRECT VARCHAR(1),
	CONSTRAINT LEDGER_ACCOUNT_PKEY PRIMARY KEY (LEDGER_ACCOUNT, START_DATE)
);
