SELECT * FROM stage.FT_BALANCE_F

SELECT * FROM stage.MD_CURRENCY_D

SELECT * FROM "DS".FT_BALANCE_F

SELECT * FROM "DS".FT_POSTING_F;

SELECT * FROM "DS".MD_ACCOUNT_D;

SELECT * FROM "DS".MD_CURRENCY_D

SELECT * FROM "DS".MD_EXCHANGE_RATE_D

SELECT * FROM "DS".MD_LEDGER_ACCOUNT_S

SELECT * FROM "LOGS".etl_log
ORDER BY log_date DESC, start_time DESC

DELETE FROM "DS".MD_CURRENCY_D;

DELETE FROM "DS".MD_ACCOUNT_D

SELECT *
FROM stage.md_currency_d
WHERE "CURRENCY_RK" IS NOT NULL
  AND "DATA_ACTUAL_DATE" IS NOT NULL;
