\c taskdb
GRANT ALL PRIVILEGES ON SCHEMA public TO bn_airflow, testus;

CREATE SCHEMA IF NOT EXISTS DS AUTHORIZATION testus;
GRANT ALL PRIVILEGES ON SCHEMA DS TO testus, bn_airflow;

CREATE SCHEMA IF NOT EXISTS LOGS AUTHORIZATION testus;
GRANT ALL PRIVILEGES ON SCHEMA LOGS TO testus, bn_airflow;
