\c taskdb

GRANT ALL PRIVILEGES ON SCHEMA DS TO testus, bn_airflow;
GRANT ALL PRIVILEGES ON all TABLES in SCHEMA DS TO testus, bn_airflow;
GRANT ALL PRIVILEGES ON all SEQUENCES in SCHEMA DS TO testus, bn_airflow;
GRANT ALL PRIVILEGES ON all FUNCTIONS in SCHEMA DS TO testus, bn_airflow;
GRANT ALL PRIVILEGES ON all PROCEDURES in SCHEMA DS TO testus, bn_airflow;
GRANT ALL PRIVILEGES ON all ROUTINES in SCHEMA DS TO testus, bn_airflow;

GRANT ALL PRIVILEGES ON SCHEMA LOGS TO testus, bn_airflow;
GRANT ALL PRIVILEGES ON all TABLES in SCHEMA LOGS TO testus, bn_airflow;
GRANT ALL PRIVILEGES ON all SEQUENCES in SCHEMA LOGS TO testus, bn_airflow;
GRANT ALL PRIVILEGES ON all FUNCTIONS in SCHEMA LOGS TO testus, bn_airflow;
GRANT ALL PRIVILEGES ON all PROCEDURES in SCHEMA LOGS TO testus, bn_airflow;
GRANT ALL PRIVILEGES ON all ROUTINES in SCHEMA LOGS TO testus, bn_airflow;

GRANT ALL PRIVILEGES ON SCHEMA DM TO testus, bn_airflow;
GRANT ALL PRIVILEGES ON all TABLES in SCHEMA DM TO testus, bn_airflow;
GRANT ALL PRIVILEGES ON all SEQUENCES in SCHEMA DM TO testus, bn_airflow;
GRANT ALL PRIVILEGES ON all FUNCTIONS in SCHEMA DM TO testus, bn_airflow;
GRANT ALL PRIVILEGES ON all PROCEDURES in SCHEMA DM TO testus, bn_airflow;
GRANT ALL PRIVILEGES ON all ROUTINES in SCHEMA DM TO testus, bn_airflow;

GRANT ALL PRIVILEGES ON SCHEMA RD TO testus, bn_airflow;
GRANT ALL PRIVILEGES ON all TABLES in SCHEMA RD TO testus, bn_airflow;
GRANT ALL PRIVILEGES ON all SEQUENCES in SCHEMA RD TO testus, bn_airflow;
GRANT ALL PRIVILEGES ON all FUNCTIONS in SCHEMA RD TO testus, bn_airflow;
GRANT ALL PRIVILEGES ON all PROCEDURES in SCHEMA RD TO testus, bn_airflow;
GRANT ALL PRIVILEGES ON all ROUTINES in SCHEMA RD TO testus, bn_airflow;
